name: MacOS GUI via tmate (hardcoded password)

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-14
    timeout-minutes: 360

    steps:
      - name: Instructions (see this in Summary)
        shell: bash
        run: |
          {
            echo "### How to connect"
            echo "1) Wait for the **tmate** step to print an SSH command like:"
            echo "   \`ssh <token>@sfo2.tmate.io\`"
            echo ""
            echo "2) On your Windows PC, run this (adds port forward):"
            echo "   \`ssh -L 5900:localhost:5900 <token>@sfo2.tmate.io\`"
            echo ""
            echo "3) Keep that SSH window open."
            echo "4) Open your VNC client and connect to **127.0.0.1:5900**"
            echo "5) Use password: **macos123**"
            echo ""
            echo "> Reminder: macOS VNC only supports legacy 8-char passwords."
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Enable VNC with hardcoded password
        shell: bash
        run: |
          set -euxo pipefail

          VNC_PASSWORD="macos123"

          # Enable Apple Remote Desktop + VNC legacy
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on \
            -clientopts -setvnclegacy -vnclegacy yes \
            -clientopts -setmenuextra -menuextra yes \
            -configure -allowAccessFor -allUsers -privs -all

          # Set VNC password (must be ≤ 8 chars)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvncpw -vncpw "$VNC_PASSWORD"

          # Ensure Screen Sharing is running
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist || true
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

          echo "VNC password set to: $VNC_PASSWORD"

      - name: Start tmate for tunneling
        uses: mxschmitt/action-tmate@v2
        with:
          limit-access-to-actor: true
